# Generated by Django 3.1.2 on 2020-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='town',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
