# Generated by Django 3.1.2 on 2020-10-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='soket',
            new_name='stock',
        ),
    ]
